# wrangler.toml (wrangler v3.78.6^)
name = "bits"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
kv_namespaces = [
  { binding = "BITS_V2RAY", id = "3e119e6834a54c239128439451341b4a" }
]
[observability]
enabled = true
